environment:
  global:
    CIBW_SKIP: "cp27-* cp35-* cp36-* pp*"
    CIBW_BUILD_VERBOSITY: 3
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"

stack: python 3.7

init:
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
- cmd: set

install: python -m pip install cibuildwheel==1.7.4

build_script: python -m cibuildwheel --output-dir wheelhouse

test_script:
  - dir
  - dir wheelhouse
  - python -m pip install -f wheelhouse/ hello
  - python sample.py

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
